package main;

import java.io.IOException;
import sun.tools.jar.CommandLine;

/**
 *
 * @author AMORRISO
 */
public class SupportForm extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public SupportForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAEDStaff = new javax.swing.ButtonGroup();
        bgAEDCR = new javax.swing.ButtonGroup();
        pnlLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        pnlLoginDetails = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        pnlHome = new javax.swing.JPanel();
        lblTitleH = new javax.swing.JLabel();
        pnlHomeButtons = new javax.swing.JPanel();
        btnStaffH = new javax.swing.JButton();
        btnCustomerH = new javax.swing.JButton();
        btnProductH = new javax.swing.JButton();
        btnLogoutH = new javax.swing.JButton();
        btnExitH = new javax.swing.JButton();
        pnlStaff = new javax.swing.JPanel();
        lblTitleS = new javax.swing.JLabel();
        pnlStaffDetails = new javax.swing.JPanel();
        cbStaffListS = new javax.swing.JComboBox<>();
        lblStaffIDS = new javax.swing.JLabel();
        txtStaffIDS = new javax.swing.JTextField();
        lblForenameS = new javax.swing.JLabel();
        txtForenameS = new javax.swing.JTextField();
        lblSurnameS = new javax.swing.JLabel();
        txtSurnameS = new javax.swing.JTextField();
        lblAddressS = new javax.swing.JLabel();
        sptxtaAddressS = new javax.swing.JScrollPane();
        txtaAddressS = new javax.swing.JTextArea();
        lblPostcodeS = new javax.swing.JLabel();
        txtPostcodeS = new javax.swing.JTextField();
        lblEmailS = new javax.swing.JLabel();
        txtEmailS = new javax.swing.JTextField();
        lblDateOfBirthS = new javax.swing.JLabel();
        dcDateOfBirthS = new com.toedter.calendar.JDateChooser();
        lblPasswordCheckS = new javax.swing.JLabel();
        pnlStaffButtons = new javax.swing.JPanel();
        rbAddS = new javax.swing.JRadioButton();
        rbEditS = new javax.swing.JRadioButton();
        rbDeleteS = new javax.swing.JRadioButton();
        btnSubmitS = new javax.swing.JButton();
        btnStaffListS = new javax.swing.JButton();
        btnHomeS = new javax.swing.JButton();
        pnlCustomerReport = new javax.swing.JPanel();
        lblTitleCR = new javax.swing.JLabel();
        spCustomerReportDetails = new javax.swing.JScrollPane();
        pnlCustomerReportDetails = new javax.swing.JPanel();
        cbReportListCR = new javax.swing.JComboBox<>();
        lblReportIDCR = new javax.swing.JLabel();
        txtReportIDCR = new javax.swing.JTextField();
        lblForenameCR = new javax.swing.JLabel();
        txtForenameCR = new javax.swing.JTextField();
        lblSurnameCR = new javax.swing.JLabel();
        txtSurnameCR = new javax.swing.JTextField();
        lblAddressCR = new javax.swing.JLabel();
        sptxtaAddressS1 = new javax.swing.JScrollPane();
        txtaAddressCR = new javax.swing.JTextArea();
        lblPostcodeCR = new javax.swing.JLabel();
        txtPostcodeCR = new javax.swing.JTextField();
        lblEmailCR = new javax.swing.JLabel();
        txtEmailCR = new javax.swing.JTextField();
        lblTelephoneCR = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        lblReportDateCR = new javax.swing.JLabel();
        dcReportDateCR = new com.toedter.calendar.JDateChooser();
        lblEquipmentTypeCR = new javax.swing.JLabel();
        cbEquipmentTypeCR = new javax.swing.JComboBox<>();
        lblNatureOfProblemCR = new javax.swing.JLabel();
        spNatureOfProblemCR = new javax.swing.JScrollPane();
        txtaNatureOfProblemCR = new javax.swing.JTextArea();
        lblSeverityCR = new javax.swing.JLabel();
        cbSeverityCR = new javax.swing.JComboBox<>();
        lblStaffAcceptingCR = new javax.swing.JLabel();
        cbStaffAcceptingCR = new javax.swing.JComboBox<>();
        lblStaffFixingCR = new javax.swing.JLabel();
        cbStaffFixingCR = new javax.swing.JComboBox<>();
        lblDateResolvedCR = new javax.swing.JLabel();
        dcDateResolvedCR = new com.toedter.calendar.JDateChooser();
        lblRepairCostCR = new javax.swing.JLabel();
        txtRepairCostCR = new javax.swing.JTextField();
        pnlCustomerReportButtons = new javax.swing.JPanel();
        rbAddCR = new javax.swing.JRadioButton();
        rbEditCR = new javax.swing.JRadioButton();
        rbDeleteCR = new javax.swing.JRadioButton();
        btnSubmitCR = new javax.swing.JButton();
        btnStaffListCR = new javax.swing.JButton();
        btnHomeCR = new javax.swing.JButton();
        pnlProductReport = new javax.swing.JPanel();
        lblTitlePD = new javax.swing.JLabel();
        spProductReportDetails = new javax.swing.JScrollPane();
        pnlProductReportDetails = new javax.swing.JPanel();
        cbProductListPR = new javax.swing.JComboBox<>();
        lblProductIDPR = new javax.swing.JLabel();
        txtProductIDPR = new javax.swing.JTextField();
        lblCustomerIDPR = new javax.swing.JLabel();
        cbCustomerIDPR = new javax.swing.JComboBox<>();
        lblStaffAcceptingPR = new javax.swing.JLabel();
        cbStaffAcceptingPR = new javax.swing.JComboBox<>();
        lblProductNamePR = new javax.swing.JLabel();
        txtProductNamePR = new javax.swing.JTextField();
        lblManufacturerPR = new javax.swing.JLabel();
        txtManufacturerPR = new javax.swing.JTextField();
        lblModelNamePR = new javax.swing.JLabel();
        txtModelNamePR = new javax.swing.JTextField();
        lblSerialNumberPR = new javax.swing.JLabel();
        txtSerialNumberPR = new javax.swing.JTextField();
        lblReportDatePR = new javax.swing.JLabel();
        dcReportDatePR = new com.toedter.calendar.JDateChooser();
        lblNatureOfProblemPR = new javax.swing.JLabel();
        spNatureOfProblemPR = new javax.swing.JScrollPane();
        txtaNatureOfProblemPR = new javax.swing.JTextArea();
        lblDateResolvedPR = new javax.swing.JLabel();
        dcDateResolvedPR = new com.toedter.calendar.JDateChooser();
        lblWorkReportPR = new javax.swing.JLabel();
        spWorkReportPR = new javax.swing.JScrollPane();
        txtaWorkReportPR = new javax.swing.JTextArea();
        pnlProductReportButtons = new javax.swing.JPanel();
        rbAddPR = new javax.swing.JRadioButton();
        rbEditPR = new javax.swing.JRadioButton();
        rbDeletePR = new javax.swing.JRadioButton();
        btnSubmitPR = new javax.swing.JButton();
        btnStaffListPR = new javax.swing.JButton();
        btnHomePR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fast Computer Fix");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblLogin.setText("Login");

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        btnSubmit.setText("Submit");

        javax.swing.GroupLayout pnlLoginDetailsLayout = new javax.swing.GroupLayout(pnlLoginDetails);
        pnlLoginDetails.setLayout(pnlLoginDetailsLayout);
        pnlLoginDetailsLayout.setHorizontalGroup(
            pnlLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginDetailsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPassword))
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit)
                    .addGroup(pnlLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtStaffID)
                        .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlLoginDetailsLayout.setVerticalGroup(
            pnlLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(34, 34, 34)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(pnlLoginDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(lblLogin)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(pnlLoginDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );

        getContentPane().add(pnlLogin, "card7");

        lblTitleH.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitleH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleH.setText("Home");

        btnStaffH.setText("Staff Accounts");

        btnCustomerH.setText("Customer Reports");

        btnProductH.setText("Product Details");

        btnLogoutH.setText("Logout");

        btnExitH.setText("Exit");

        javax.swing.GroupLayout pnlHomeButtonsLayout = new javax.swing.GroupLayout(pnlHomeButtons);
        pnlHomeButtons.setLayout(pnlHomeButtonsLayout);
        pnlHomeButtonsLayout.setHorizontalGroup(
            pnlHomeButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeButtonsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlHomeButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCustomerH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogoutH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExitH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaffH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlHomeButtonsLayout.setVerticalGroup(
            pnlHomeButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeButtonsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnStaffH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCustomerH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProductH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogoutH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExitH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lblTitleH, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(pnlHomeButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitleH, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlHomeButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        getContentPane().add(pnlHome, "pnlHome");

        lblTitleS.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitleS.setText("Staff Accounts");

        cbStaffListS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an Existing Staff ID..." }));
        cbStaffListS.setToolTipText("If you need to edit your details select your ID from the drop-down list.");

        lblStaffIDS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStaffIDS.setText("Staff ID:");

        txtStaffIDS.setEditable(false);

        lblForenameS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblForenameS.setText("Forename:");

        lblSurnameS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSurnameS.setText("Surname:");

        lblAddressS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAddressS.setText("Address:");

        txtaAddressS.setColumns(20);
        txtaAddressS.setRows(5);
        sptxtaAddressS.setViewportView(txtaAddressS);

        lblPostcodeS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPostcodeS.setText("Postcode:");

        lblEmailS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmailS.setText("Email:");

        lblDateOfBirthS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDateOfBirthS.setText("Date Of Birth:");

        lblPasswordCheckS.setText("Password Set = False");

        javax.swing.GroupLayout pnlStaffDetailsLayout = new javax.swing.GroupLayout(pnlStaffDetails);
        pnlStaffDetails.setLayout(pnlStaffDetailsLayout);
        pnlStaffDetailsLayout.setHorizontalGroup(
            pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStaffDetailsLayout.createSequentialGroup()
                .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStaffDetailsLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlStaffDetailsLayout.createSequentialGroup()
                                .addComponent(lblSurnameS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSurnameS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlStaffDetailsLayout.createSequentialGroup()
                                .addComponent(lblAddressS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sptxtaAddressS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStaffDetailsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblForenameS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStaffIDS, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStaffIDS)
                            .addComponent(txtForenameS)
                            .addComponent(cbStaffListS, 0, 170, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(pnlStaffDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlStaffDetailsLayout.createSequentialGroup()
                        .addComponent(lblPostcodeS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPostcodeS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlStaffDetailsLayout.createSequentialGroup()
                        .addComponent(lblEmailS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlStaffDetailsLayout.createSequentialGroup()
                        .addComponent(lblDateOfBirthS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasswordCheckS)
                            .addComponent(dcDateOfBirthS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStaffDetailsLayout.setVerticalGroup(
            pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbStaffListS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStaffIDS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaffIDS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForenameS)
                    .addComponent(txtForenameS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurnameS)
                    .addComponent(txtSurnameS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sptxtaAddressS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostcodeS)
                    .addComponent(txtPostcodeS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcDateOfBirthS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDateOfBirthS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblPasswordCheckS)
                .addContainerGap())
        );

        bgAEDStaff.add(rbAddS);
        rbAddS.setText("Add");

        bgAEDStaff.add(rbEditS);
        rbEditS.setText("Edit");

        bgAEDStaff.add(rbDeleteS);
        rbDeleteS.setText("Delete");

        btnSubmitS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmitS.setText("Submit");

        btnStaffListS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStaffListS.setText("Staff List");

        btnHomeS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHomeS.setText("Home");

        javax.swing.GroupLayout pnlStaffButtonsLayout = new javax.swing.GroupLayout(pnlStaffButtons);
        pnlStaffButtons.setLayout(pnlStaffButtonsLayout);
        pnlStaffButtonsLayout.setHorizontalGroup(
            pnlStaffButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStaffButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbDeleteS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbEditS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbAddS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlStaffButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHomeS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubmitS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaffListS, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlStaffButtonsLayout.setVerticalGroup(
            pnlStaffButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffButtonsLayout.createSequentialGroup()
                .addGroup(pnlStaffButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStaffButtonsLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(rbAddS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbEditS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDeleteS))
                    .addGroup(pnlStaffButtonsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSubmitS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStaffListS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHomeS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlStaffLayout = new javax.swing.GroupLayout(pnlStaff);
        pnlStaff.setLayout(pnlStaffLayout);
        pnlStaffLayout.setHorizontalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStaffLayout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(lblTitleS)
                .addGap(210, 210, 210))
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(pnlStaffDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlStaffButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStaffLayout.setVerticalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStaffDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStaffLayout.createSequentialGroup()
                        .addComponent(pnlStaffButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(pnlStaff, "pnlStaff");

        lblTitleCR.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitleCR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleCR.setText("Customer Reports");

        cbReportListCR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an Existing Report ID..." }));
        cbReportListCR.setToolTipText("If you need to edit your details select your ID from the drop-down list.");

        lblReportIDCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblReportIDCR.setText("Report ID:");

        txtReportIDCR.setEditable(false);

        lblForenameCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblForenameCR.setText("Forename:");

        lblSurnameCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSurnameCR.setText("Surname:");

        lblAddressCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAddressCR.setText("Address:");

        txtaAddressCR.setColumns(20);
        txtaAddressCR.setRows(5);
        sptxtaAddressS1.setViewportView(txtaAddressCR);

        lblPostcodeCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPostcodeCR.setText("Postcode:");

        lblEmailCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmailCR.setText("Email:");

        lblTelephoneCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTelephoneCR.setText("Telephone:");

        lblReportDateCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblReportDateCR.setText("Report Date:");

        lblEquipmentTypeCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEquipmentTypeCR.setText("Equipment Type:");

        cbEquipmentTypeCR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an Equipment Type...", "Computer", "Printer", "Router", "Switch", "Monitor" }));

        lblNatureOfProblemCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNatureOfProblemCR.setText("Nature Of Problem:");

        txtaNatureOfProblemCR.setColumns(20);
        txtaNatureOfProblemCR.setRows(5);
        spNatureOfProblemCR.setViewportView(txtaNatureOfProblemCR);

        lblSeverityCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSeverityCR.setText("Severity:");

        cbSeverityCR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Severity Level...", "1 (High)", "2 (Medium)", "3 (Low)" }));

        lblStaffAcceptingCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStaffAcceptingCR.setText("Staff Receiving Equipment:");

        cbStaffAcceptingCR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Staff Member..." }));

        lblStaffFixingCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStaffFixingCR.setText("Staff Assigned to Fix:");

        cbStaffFixingCR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Staff Member..." }));

        lblDateResolvedCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDateResolvedCR.setText("Date Resolved:");

        lblRepairCostCR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRepairCostCR.setText("Estimated Cost of Repair:");

        javax.swing.GroupLayout pnlCustomerReportDetailsLayout = new javax.swing.GroupLayout(pnlCustomerReportDetails);
        pnlCustomerReportDetails.setLayout(pnlCustomerReportDetailsLayout);
        pnlCustomerReportDetailsLayout.setHorizontalGroup(
            pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerReportDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerReportDetailsLayout.createSequentialGroup()
                        .addComponent(lblSurnameCR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSurnameCR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerReportDetailsLayout.createSequentialGroup()
                        .addComponent(lblAddressCR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sptxtaAddressS1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerReportDetailsLayout.createSequentialGroup()
                        .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblForenameCR, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblReportIDCR, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtReportIDCR)
                            .addComponent(txtForenameCR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerReportDetailsLayout.createSequentialGroup()
                        .addComponent(lblTelephoneCR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerReportDetailsLayout.createSequentialGroup()
                        .addComponent(lblPostcodeCR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPostcodeCR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerReportDetailsLayout.createSequentialGroup()
                        .addComponent(lblEmailCR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailCR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbReportListCR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerReportDetailsLayout.createSequentialGroup()
                        .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReportDateCR, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEquipmentTypeCR, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbEquipmentTypeCR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcReportDateCR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerReportDetailsLayout.createSequentialGroup()
                        .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNatureOfProblemCR)
                            .addComponent(lblSeverityCR)
                            .addComponent(lblStaffAcceptingCR)
                            .addComponent(lblStaffFixingCR)
                            .addComponent(lblDateResolvedCR)
                            .addComponent(lblRepairCostCR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRepairCostCR)
                            .addComponent(dcDateResolvedCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbStaffFixingCR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbStaffAcceptingCR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spNatureOfProblemCR)
                            .addComponent(cbSeverityCR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCustomerReportDetailsLayout.setVerticalGroup(
            pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerReportDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbReportListCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportIDCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReportIDCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForenameCR)
                    .addComponent(txtForenameCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurnameCR)
                    .addComponent(txtSurnameCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sptxtaAddressS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressCR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostcodeCR)
                    .addComponent(txtPostcodeCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailCR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephoneCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReportDateCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcReportDateCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEquipmentTypeCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEquipmentTypeCR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spNatureOfProblemCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNatureOfProblemCR, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSeverityCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeverityCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStaffAcceptingCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStaffAcceptingCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStaffFixingCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStaffFixingCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDateResolvedCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcDateResolvedCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRepairCostCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRepairCostCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spCustomerReportDetails.setViewportView(pnlCustomerReportDetails);

        bgAEDCR.add(rbAddCR);
        rbAddCR.setText("Add");

        bgAEDCR.add(rbEditCR);
        rbEditCR.setText("Edit");

        bgAEDCR.add(rbDeleteCR);
        rbDeleteCR.setText("Delete");

        btnSubmitCR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmitCR.setText("Submit");

        btnStaffListCR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStaffListCR.setText("Report List");

        btnHomeCR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHomeCR.setText("Home");

        javax.swing.GroupLayout pnlCustomerReportButtonsLayout = new javax.swing.GroupLayout(pnlCustomerReportButtons);
        pnlCustomerReportButtons.setLayout(pnlCustomerReportButtonsLayout);
        pnlCustomerReportButtonsLayout.setHorizontalGroup(
            pnlCustomerReportButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerReportButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomerReportButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbDeleteCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbEditCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbAddCR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerReportButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHomeCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubmitCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaffListCR, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCustomerReportButtonsLayout.setVerticalGroup(
            pnlCustomerReportButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerReportButtonsLayout.createSequentialGroup()
                .addGroup(pnlCustomerReportButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerReportButtonsLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(rbAddCR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbEditCR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDeleteCR))
                    .addGroup(pnlCustomerReportButtonsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSubmitCR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStaffListCR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHomeCR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCustomerReportLayout = new javax.swing.GroupLayout(pnlCustomerReport);
        pnlCustomerReport.setLayout(pnlCustomerReportLayout);
        pnlCustomerReportLayout.setHorizontalGroup(
            pnlCustomerReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerReportLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(lblTitleCR, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(pnlCustomerReportLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(spCustomerReportDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCustomerReportButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCustomerReportLayout.setVerticalGroup(
            pnlCustomerReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleCR)
                .addGroup(pnlCustomerReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerReportLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(pnlCustomerReportButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCustomerReportLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(spCustomerReportDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(pnlCustomerReport, "pnlCustomerReport");

        lblTitlePD.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitlePD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePD.setText("Product Details");

        cbProductListPR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an Existing Product ID.." }));
        cbProductListPR.setToolTipText("If you need to edit your details select your ID from the drop-down list.");

        lblProductIDPR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductIDPR.setText("Product ID:");

        txtProductIDPR.setEditable(false);

        lblCustomerIDPR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCustomerIDPR.setText("Customer ID:");

        cbCustomerIDPR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Customer ID..." }));

        lblStaffAcceptingPR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStaffAcceptingPR.setText("Staff Receiving Equipment:");

        cbStaffAcceptingPR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Staff Member..." }));

        lblProductNamePR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductNamePR.setText("Product Name:");

        lblManufacturerPR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblManufacturerPR.setText("Manufacturer:");

        lblModelNamePR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblModelNamePR.setText("Model Name/Number:");

        lblSerialNumberPR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSerialNumberPR.setText("Serial Number:");

        lblReportDatePR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblReportDatePR.setText("Report Date:");

        lblNatureOfProblemPR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNatureOfProblemPR.setText("Nature Of Problem:");

        txtaNatureOfProblemPR.setColumns(20);
        txtaNatureOfProblemPR.setRows(5);
        spNatureOfProblemPR.setViewportView(txtaNatureOfProblemPR);

        lblDateResolvedPR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDateResolvedPR.setText("Date Resolved:");

        lblWorkReportPR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWorkReportPR.setText("Work Report:");

        txtaWorkReportPR.setColumns(20);
        txtaWorkReportPR.setRows(5);
        spWorkReportPR.setViewportView(txtaWorkReportPR);

        javax.swing.GroupLayout pnlProductReportDetailsLayout = new javax.swing.GroupLayout(pnlProductReportDetails);
        pnlProductReportDetails.setLayout(pnlProductReportDetailsLayout);
        pnlProductReportDetailsLayout.setHorizontalGroup(
            pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductReportDetailsLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(cbProductListPR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductReportDetailsLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblProductIDPR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProductIDPR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportDetailsLayout.createSequentialGroup()
                            .addComponent(lblReportDatePR)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dcReportDatePR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportDetailsLayout.createSequentialGroup()
                            .addComponent(lblStaffAcceptingPR)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbStaffAcceptingPR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportDetailsLayout.createSequentialGroup()
                            .addComponent(lblCustomerIDPR)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbCustomerIDPR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportDetailsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportDetailsLayout.createSequentialGroup()
                                .addComponent(lblModelNamePR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModelNamePR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportDetailsLayout.createSequentialGroup()
                                .addComponent(lblManufacturerPR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtManufacturerPR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportDetailsLayout.createSequentialGroup()
                                .addComponent(lblSerialNumberPR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSerialNumberPR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportDetailsLayout.createSequentialGroup()
                                .addComponent(lblProductNamePR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProductNamePR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportDetailsLayout.createSequentialGroup()
                                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNatureOfProblemPR)
                                    .addComponent(lblDateResolvedPR))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dcDateResolvedPR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spNatureOfProblemPR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportDetailsLayout.createSequentialGroup()
                                .addComponent(lblWorkReportPR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spWorkReportPR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlProductReportDetailsLayout.setVerticalGroup(
            pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductReportDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbProductListPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductIDPR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductIDPR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCustomerIDPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerIDPR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStaffAcceptingPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStaffAcceptingPR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductNamePR)
                    .addComponent(txtProductNamePR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufacturerPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManufacturerPR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelNamePR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelNamePR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNumberPR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerialNumberPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReportDatePR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcReportDatePR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spNatureOfProblemPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNatureOfProblemPR, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDateResolvedPR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcDateResolvedPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductReportDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spWorkReportPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWorkReportPR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spProductReportDetails.setViewportView(pnlProductReportDetails);

        bgAEDCR.add(rbAddPR);
        rbAddPR.setSelected(true);
        rbAddPR.setText("Add");

        bgAEDCR.add(rbEditPR);
        rbEditPR.setText("Edit");

        bgAEDCR.add(rbDeletePR);
        rbDeletePR.setText("Delete");

        btnSubmitPR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmitPR.setText("Submit");

        btnStaffListPR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStaffListPR.setText("Report List");

        btnHomePR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHomePR.setText("Home");

        javax.swing.GroupLayout pnlProductReportButtonsLayout = new javax.swing.GroupLayout(pnlProductReportButtons);
        pnlProductReportButtons.setLayout(pnlProductReportButtonsLayout);
        pnlProductReportButtonsLayout.setHorizontalGroup(
            pnlProductReportButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductReportButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductReportButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbDeletePR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbEditPR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbAddPR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProductReportButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHomePR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubmitPR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaffListPR, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProductReportButtonsLayout.setVerticalGroup(
            pnlProductReportButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductReportButtonsLayout.createSequentialGroup()
                .addGroup(pnlProductReportButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductReportButtonsLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(rbAddPR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbEditPR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDeletePR))
                    .addGroup(pnlProductReportButtonsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSubmitPR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStaffListPR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHomePR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlProductReportLayout = new javax.swing.GroupLayout(pnlProductReport);
        pnlProductReport.setLayout(pnlProductReportLayout);
        pnlProductReportLayout.setHorizontalGroup(
            pnlProductReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductReportLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(lblTitlePD, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(pnlProductReportLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(spProductReportDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlProductReportButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProductReportLayout.setVerticalGroup(
            pnlProductReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitlePD)
                .addGroup(pnlProductReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductReportLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spProductReportDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductReportLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(pnlProductReportButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(pnlProductReport, "pnlProductReport");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAEDCR;
    private javax.swing.ButtonGroup bgAEDStaff;
    private javax.swing.JButton btnCustomerH;
    private javax.swing.JButton btnExitH;
    private javax.swing.JButton btnHomeCR;
    private javax.swing.JButton btnHomePR;
    private javax.swing.JButton btnHomeS;
    private javax.swing.JButton btnLogoutH;
    private javax.swing.JButton btnProductH;
    private javax.swing.JButton btnStaffH;
    private javax.swing.JButton btnStaffListCR;
    private javax.swing.JButton btnStaffListPR;
    private javax.swing.JButton btnStaffListS;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmitCR;
    private javax.swing.JButton btnSubmitPR;
    private javax.swing.JButton btnSubmitS;
    private javax.swing.JComboBox<String> cbCustomerIDPR;
    private javax.swing.JComboBox<String> cbEquipmentTypeCR;
    private javax.swing.JComboBox<String> cbProductListPR;
    private javax.swing.JComboBox<String> cbReportListCR;
    private javax.swing.JComboBox<String> cbSeverityCR;
    private javax.swing.JComboBox<String> cbStaffAcceptingCR;
    private javax.swing.JComboBox<String> cbStaffAcceptingPR;
    private javax.swing.JComboBox<String> cbStaffFixingCR;
    private javax.swing.JComboBox<String> cbStaffListS;
    private com.toedter.calendar.JDateChooser dcDateOfBirthS;
    private com.toedter.calendar.JDateChooser dcDateResolvedCR;
    private com.toedter.calendar.JDateChooser dcDateResolvedPR;
    private com.toedter.calendar.JDateChooser dcReportDateCR;
    private com.toedter.calendar.JDateChooser dcReportDatePR;
    private javax.swing.JLabel lblAddressCR;
    private javax.swing.JLabel lblAddressS;
    private javax.swing.JLabel lblCustomerIDPR;
    private javax.swing.JLabel lblDateOfBirthS;
    private javax.swing.JLabel lblDateResolvedCR;
    private javax.swing.JLabel lblDateResolvedPR;
    private javax.swing.JLabel lblEmailCR;
    private javax.swing.JLabel lblEmailS;
    private javax.swing.JLabel lblEquipmentTypeCR;
    private javax.swing.JLabel lblForenameCR;
    private javax.swing.JLabel lblForenameS;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblManufacturerPR;
    private javax.swing.JLabel lblModelNamePR;
    private javax.swing.JLabel lblNatureOfProblemCR;
    private javax.swing.JLabel lblNatureOfProblemPR;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordCheckS;
    private javax.swing.JLabel lblPostcodeCR;
    private javax.swing.JLabel lblPostcodeS;
    private javax.swing.JLabel lblProductIDPR;
    private javax.swing.JLabel lblProductNamePR;
    private javax.swing.JLabel lblRepairCostCR;
    private javax.swing.JLabel lblReportDateCR;
    private javax.swing.JLabel lblReportDatePR;
    private javax.swing.JLabel lblReportIDCR;
    private javax.swing.JLabel lblSerialNumberPR;
    private javax.swing.JLabel lblSeverityCR;
    private javax.swing.JLabel lblStaffAcceptingCR;
    private javax.swing.JLabel lblStaffAcceptingPR;
    private javax.swing.JLabel lblStaffFixingCR;
    private javax.swing.JLabel lblStaffIDS;
    private javax.swing.JLabel lblSurnameCR;
    private javax.swing.JLabel lblSurnameS;
    private javax.swing.JLabel lblTelephoneCR;
    private javax.swing.JLabel lblTitleCR;
    private javax.swing.JLabel lblTitleH;
    private javax.swing.JLabel lblTitlePD;
    private javax.swing.JLabel lblTitleS;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWorkReportPR;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPanel pnlCustomerReport;
    private javax.swing.JPanel pnlCustomerReportButtons;
    private javax.swing.JPanel pnlCustomerReportDetails;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlHomeButtons;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLoginDetails;
    private javax.swing.JPanel pnlProductReport;
    private javax.swing.JPanel pnlProductReportButtons;
    private javax.swing.JPanel pnlProductReportDetails;
    private javax.swing.JPanel pnlStaff;
    private javax.swing.JPanel pnlStaffButtons;
    private javax.swing.JPanel pnlStaffDetails;
    private javax.swing.JRadioButton rbAddCR;
    private javax.swing.JRadioButton rbAddPR;
    private javax.swing.JRadioButton rbAddS;
    private javax.swing.JRadioButton rbDeleteCR;
    private javax.swing.JRadioButton rbDeletePR;
    private javax.swing.JRadioButton rbDeleteS;
    private javax.swing.JRadioButton rbEditCR;
    private javax.swing.JRadioButton rbEditPR;
    private javax.swing.JRadioButton rbEditS;
    private javax.swing.JScrollPane spCustomerReportDetails;
    private javax.swing.JScrollPane spNatureOfProblemCR;
    private javax.swing.JScrollPane spNatureOfProblemPR;
    private javax.swing.JScrollPane spProductReportDetails;
    private javax.swing.JScrollPane spWorkReportPR;
    private javax.swing.JScrollPane sptxtaAddressS;
    private javax.swing.JScrollPane sptxtaAddressS1;
    private javax.swing.JTextField txtEmailCR;
    private javax.swing.JTextField txtEmailS;
    private javax.swing.JTextField txtForenameCR;
    private javax.swing.JTextField txtForenameS;
    private javax.swing.JTextField txtManufacturerPR;
    private javax.swing.JTextField txtModelNamePR;
    private javax.swing.JTextField txtPostcodeCR;
    private javax.swing.JTextField txtPostcodeS;
    private javax.swing.JTextField txtProductIDPR;
    private javax.swing.JTextField txtProductNamePR;
    private javax.swing.JTextField txtRepairCostCR;
    private javax.swing.JTextField txtReportIDCR;
    private javax.swing.JTextField txtSerialNumberPR;
    private javax.swing.JTextField txtStaffID;
    private javax.swing.JTextField txtStaffIDS;
    private javax.swing.JTextField txtSurnameCR;
    private javax.swing.JTextField txtSurnameS;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextArea txtaAddressCR;
    private javax.swing.JTextArea txtaAddressS;
    private javax.swing.JTextArea txtaNatureOfProblemCR;
    private javax.swing.JTextArea txtaNatureOfProblemPR;
    private javax.swing.JTextArea txtaWorkReportPR;
    // End of variables declaration//GEN-END:variables
}
